// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;
using UnityEditor;




public class DecompilerWindow : XBaseWindow
{
    
	[MenuItem( "Wuxingogo/DecompilerWindow" )]
	static void Initialization()
	{
		InitWindow<DecompilerWindow>();
	}

	public override void OnXGUI()
	{
		DoButton( "Decompiler", Decompiler );
	}

	void Decompiler()
	{

	}
}
