// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;
using UnityEditor;
using System;


class IconWindow : XBaseWindow
{
	static string[] text;

	[MenuItem( "Wuxingogo/IconWindow" )]
 
	public static void ShowWindow()
	{
		EditorWindow.GetWindow( typeof( IconWindow ) );
		text = Resources.Load<TextAsset>( "myText" ).text.Split( "\n"[0] );
	}

	public Vector2 scrollPosition;

	public override void OnXGUI()
	{
 
		scrollPosition = GUILayout.BeginScrollView( scrollPosition );
 
		//鼠标放在按钮上的样式
		foreach( MouseCursor item in Enum.GetValues(typeof(MouseCursor)) ) {
			GUILayout.Button( Enum.GetName( typeof( MouseCursor ), item ) );
			EditorGUIUtility.AddCursorRect( GUILayoutUtility.GetLastRect(), item );
			GUILayout.Space( 10 );
		}
 
 
		//内置图标
		for( int i = 0; i < text.Length; i += 8 ) {
			GUILayout.BeginHorizontal();
			for( int j = 0; j < 8; j++ ) {
				int index = i + j;
				if( index < text.Length )
				if( GUILayout.Button( EditorGUIUtility.IconContent( text[index] ), GUILayout.Width( 50 ), GUILayout.Height( 30 ) ) )
					Debug.Log( text[index] );
			}
			GUILayout.EndHorizontal();
		}
        
 
 
 
		GUILayout.EndScrollView();
	}
}
